"""Data integrity tests over the REAL word_bank/ files (data/word_bank/*.json).

These are git-tracked source data (regenerated by scripts/build_wordbanks.py from
scripts/raw_words.py) — 736 words across 9 patterns, each entry enriched with a
phonics-derived difficulty score. This suite guards the shape/consistency
contract that engine/selector.py and the exercise UI depend on, independent of
the temp-data-root fixtures used elsewhere (this reads the actual repo files).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from engine import store  # noqa: E402
from engine.config import SKILL_IDS  # noqa: E402

REAL_WORD_BANK_DIR = REPO_ROOT / "data" / "word_bank"

# Real word_bank/*.json files, excluding skill_graph.json (not a word bank —
# it's the prerequisite graph, with no "pattern"/"words" keys).
_BANK_FILES = sorted(
    p for p in REAL_WORD_BANK_DIR.glob("*.json") if p.stem != "skill_graph"
)

REQUIRED_ENTRY_KEYS = {"word", "phonemes", "pattern", "difficulty", "tricky_letters", "distractors"}


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


@pytest.fixture(scope="module")
def bank_docs():
    """{filename_stem: parsed_json} for every real word bank file (no skill_graph)."""
    return {p.stem: _load(p) for p in _BANK_FILES}


def test_word_bank_directory_uses_real_store_path():
    # sanity: store.WORD_BANK_DIR (unpatched, module-level default) points at the
    # same real data/word_bank/ directory this suite reads directly.
    assert store.WORD_BANK_DIR.resolve() == REAL_WORD_BANK_DIR.resolve()


def test_at_least_one_bank_file_found():
    assert len(_BANK_FILES) > 0


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_top_level_pattern_matches_filename_stem(path):
    doc = _load(path)
    assert doc["pattern"] == path.stem


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_entries_have_required_keys(path):
    doc = _load(path)
    for entry in doc["words"]:
        missing = REQUIRED_ENTRY_KEYS - entry.keys()
        assert not missing, f"{path.stem}: word {entry.get('word')!r} missing {missing}"


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_words_are_lowercase_alphabetic(path):
    doc = _load(path)
    for entry in doc["words"]:
        word = entry["word"]
        assert word == word.lower(), f"{path.stem}: {word!r} is not lowercase"
        assert word.isalpha(), f"{path.stem}: {word!r} is not alphabetic"


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_phonemes_non_empty_list(path):
    doc = _load(path)
    for entry in doc["words"]:
        phonemes = entry["phonemes"]
        assert isinstance(phonemes, list)
        assert len(phonemes) > 0, f"{path.stem}: {entry['word']!r} has empty phonemes"


@pytest.mark.parametrize(
    "path", [p for p in _BANK_FILES if p.stem != "heart_words"], ids=lambda p: p.stem
)
def test_bank_phonemes_rejoin_to_word_for_regular_patterns(path):
    # heart_words is excluded: those entries may use sound-based phonemes that
    # don't literally rejoin to the spelling (e.g. "of" -> ["o", "v"]).
    doc = _load(path)
    for entry in doc["words"]:
        joined = "".join(entry["phonemes"])
        assert joined == entry["word"], (
            f"{path.stem}: {entry['word']!r} phonemes {entry['phonemes']!r} "
            f"join to {joined!r}"
        )


def test_heart_words_phonemes_need_not_rejoin_but_must_be_nonempty_strings():
    doc = _load(REAL_WORD_BANK_DIR / "heart_words.json")
    for entry in doc["words"]:
        assert isinstance(entry["phonemes"], list)
        assert all(isinstance(p, str) and p for p in entry["phonemes"])


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_difficulty_is_int_in_1_to_5(path):
    doc = _load(path)
    for entry in doc["words"]:
        d = entry["difficulty"]
        assert isinstance(d, int) and not isinstance(d, bool), (
            f"{path.stem}: {entry['word']!r} difficulty {d!r} is not an int"
        )
        assert 1 <= d <= 5, f"{path.stem}: {entry['word']!r} difficulty {d} out of range"


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_entry_pattern_matches_file_pattern(path):
    doc = _load(path)
    for entry in doc["words"]:
        assert entry["pattern"] == path.stem, (
            f"{path.stem}: {entry['word']!r} has pattern {entry['pattern']!r}"
        )


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_no_duplicate_words_within_bank(path):
    doc = _load(path)
    words = [entry["word"] for entry in doc["words"]]
    dupes = {w for w in words if words.count(w) > 1}
    assert not dupes, f"{path.stem}: duplicate words {dupes}"


@pytest.mark.parametrize("path", _BANK_FILES, ids=lambda p: p.stem)
def test_bank_tricky_letters_and_distractors_are_lists(path):
    doc = _load(path)
    for entry in doc["words"]:
        assert isinstance(entry["tricky_letters"], list), (
            f"{path.stem}: {entry['word']!r} tricky_letters not a list"
        )
        assert isinstance(entry["distractors"], list), (
            f"{path.stem}: {entry['word']!r} distractors not a list"
        )


def test_skill_graph_has_all_14_skill_ids_as_keys():
    graph = _load(REAL_WORD_BANK_DIR / "skill_graph.json")
    assert set(graph.keys()) == set(SKILL_IDS)
    assert len(SKILL_IDS) == 14


def test_skill_graph_prereq_values_are_lists_of_known_skill_ids():
    graph = _load(REAL_WORD_BANK_DIR / "skill_graph.json")
    for skill_id, prereqs in graph.items():
        assert isinstance(prereqs, list)
        for p in prereqs:
            assert p in SKILL_IDS, f"{skill_id}: unknown prereq {p!r}"


def test_total_word_count_across_all_banks_at_least_500():
    total = sum(len(_load(p)["words"]) for p in _BANK_FILES)
    assert total >= 500


def test_bank_files_count_matches_expected_pattern_set():
    # sanity per the task brief: 736 words across 9 patterns (word_sequencing,
    # phrase_dictation, sentence_writing have no standalone word bank file yet —
    # they compose from other patterns' words).
    assert len(_BANK_FILES) == 9
